version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/anime-list
hooks:
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 3000
      runas: ec2-user
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 3000
      runas: ec2-user
